using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DummyApiExample.Models
{
    public class UserPreview
    {

        public string Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Picture { get; set; }
        /*
         * id: string(autogenerated)
title: string("mr", "ms", "mrs", "miss", "dr", "")
firstName: string(length: 2-50)
lastName: string(length: 2-50)
picture: string(url)*/
    }
}